.TH RVIM 1
.SH NAME
rvim \- A text editor in rust.
.SH SYNOPSIS
\fBrvim\fR path
.SH FEATURES
Syntax Highlighting:
    includes syntax highlighting for languages like:
    \- Bash (.sh)
    \- C (.c, .h)
    \- C++ (.cc, .cpp, .C, .h, .hh, .hpp)
    \- Javascript (.js)
    \- Python (.py)
    \- Ruby (.rb)
    \- Rust (.rs)


.SH EXIT STATUS
.TP
\fB0\fR
Successful program execution.

.TP
\fB1\fR
Unsuccessful program execution.

.TP
\fB101\fR
The program panicked.
.SH EXAMPLES
.TP
Running the program
\fB$ rvim [FILE]...\fR
.br
TODO

.SH AUTHOR
.P
.RS 2
.nf
Takashi I <mail@takashiidobe.com>
